# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hpowlows <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/02 11:58:11 by hpowlows          #+#    #+#              #
#    Updated: 2018/10/02 11:58:16 by hpowlows         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

all:
	@gcc -Wall -Wextra -Werror operations.c \
		main.c -o $(NAME)

clean:
	@rm -f main.o \
		operations.o 
		
